'use client'
import { useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { MaterialUISwitch } from '@/components/loaders'
import Navbar from '@/components/navbar'
import { usePathname } from 'next/navigation'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const [mode,setMode]=useState(false)
  const params=usePathname()
  
    return (
    <html lang="en">
      <body className={`${inter.className} ${mode?'dark':null}`}>
        <div className='flex'>
          {params!=='/login'?<Navbar/>:null}
        {children}
          </div>
        <button onClick={()=>setMode(!mode)} className=' fixed left-5 bottom-28'>
          <MaterialUISwitch/>
        </button>
        </body>
    </html>
  )
}
